// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB85_VcBRqJDG2V4EEW6ijY16EiGG0LLk4',
    appId: '1:185567454577:web:4d413218fa08f0c11782d0',
    messagingSenderId: '185567454577',
    projectId: 'chatapp-c079f',
    authDomain: 'chatapp-c079f.firebaseapp.com',
    storageBucket: 'chatapp-c079f.appspot.com',
    measurementId: 'G-VKQ3MK1PHP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPVe4-wBKZx-gZAPuQF_fs7JM4tnnu-ls',
    appId: '1:185567454577:android:af4893e0e6fd7ddf1782d0',
    messagingSenderId: '185567454577',
    projectId: 'chatapp-c079f',
    storageBucket: 'chatapp-c079f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeWOQSRMWfMTfpfpM8bPzPcUWns49TJcs',
    appId: '1:185567454577:ios:f8625c9ab731f95e1782d0',
    messagingSenderId: '185567454577',
    projectId: 'chatapp-c079f',
    storageBucket: 'chatapp-c079f.appspot.com',
    androidClientId: '185567454577-9oj5k9omt9d2gcl06qin81f25i4hg0ru.apps.googleusercontent.com',
    iosClientId: '185567454577-gq4k90d3o6arvor3ru7p40glm80vekjc.apps.googleusercontent.com',
    iosBundleId: 'com.duytq.flutterchatdemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeWOQSRMWfMTfpfpM8bPzPcUWns49TJcs',
    appId: '1:185567454577:ios:2453585c6c4bd4d61782d0',
    messagingSenderId: '185567454577',
    projectId: 'chatapp-c079f',
    storageBucket: 'chatapp-c079f.appspot.com',
    androidClientId: '185567454577-9oj5k9omt9d2gcl06qin81f25i4hg0ru.apps.googleusercontent.com',
    iosClientId: '185567454577-04f6gectusq5nekfvq4k520p5a9veig5.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
